# Тут указывается используемый в проекте язык программирования, можно указать несколько
language: python

# Далее, укажите версии python для которых нужно производить сборки
python:
  - "3.5"

# Параметры окружения
env:
  - FLASK_CONFIG=development
  - FLASK_APP=backend/run.py

# Команда для установки зависимостей в окружение (при этом доступны переменные из секции "env")
install:
  - pip3 install -r backend/requirements.txt


# Команда для запуска тестов, в моем случае они запускаются именно так
#script: python multi_sessions/tests.py
