version: "3"
services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5454:5432"

  loader:
    build:
      context: ../loader/
    volumes:
      - ../src/database:/tmp/database
    env_file: .env
    depends_on:
      - postgres
