@startuml

player: player_id [INT]
player: nickname [TEXT]
player: first_name [TEXT]
player: surname [TEXT]
player: about [TEXT]
player: email [TEXT]
player: password [TEXT]
player: kills [INT]
player: deaths [INT]

player: team_id [INT]
player --> stats
player --> team

team: team_id [INT]
team: title [TEXT]
team: games_win [INT]
team: games_lose [INT]
team: games_draw [INT]

game: game_id [INT]
game: team_1_id [INT]
game: team_2_id [INT]
game: points_1 [INT]
game: points_2 [INT]
game --> team: team1
game --> team: team2

tournament: tournament_id [INT]
tournament: title [TEXT]
tournament: date_starts [DATETIME]
tournament: date_ends [DATETIME]
tournament: teams []
tournament --> team: arrayof teams in tourn

@enduml